diff animaltest.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/animaltest.xml
diff auxin.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/auxin.xml
diff cochrane.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/cochrane.xml
diff compchem.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/compchem.xml
diff country.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/country.xml
diff crispr.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/crispr.xml
diff crystal.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/crystal.xml
diff disease.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/disease.xml
diff distributions.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/distributions.xml
diff diterpene.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/diterpene.xml
diff drugs.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/drugs.xml
diff elements.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/elements.xml
diff epidemic.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/epidemic.xml
diff eurofunders.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/eurofunders.xml
diff funders.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/funders.xml
diff hgnc.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/hgnc.xml
diff illegaldrugs.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/illegaldrugs.xml
diff inn.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/inn.xml
diff insecticide.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/insecticide.xml
diff instrumentManufacturer.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/instrumentManufacturer.xml
diff invasive.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/invasive.xml
diff jax.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/jax.xml
diff magnetism.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/magnetism.xml
diff monoterpene.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/monoterpene.xml
diff nal.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/nal.xml
diff nmrspectroscopy.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/nmrspectroscopy.xml
diff obesity.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/obesity.xml
diff organization.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/organization.xml
diff pectin.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/pectin.xml
diff photosynth.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/photosynth.xml
diff phytochemicals.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/phytochemicals.xml
diff plantDevelopment.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/plantDevelopment.xml
diff plantparts.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/plantparts.xml
diff poverty.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/poverty.xml
diff refugeeUNHCR.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/refugeeUNHCR.xml
diff sesquiterpene.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/sesquiterpene.xml
diff solvents.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/solvents.xml
diff statistics.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/statistics.xml
diff synbio.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/synbio.xml
diff taxdumpGenus.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/taxdumpGenus.xml
diff terpenesynthase.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/terpenesynthase.xml
diff triterpene.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/triterpene.xml
diff tropicalVirus.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/tropicalVirus.xml
diff wetlands.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/wetlands.xml
diff wildlife.xml ~/workspace/cmdev/normami/src/main/resources/org/contentmine/ami/plugins/dictionary/wildlife.xml
